version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: school-app_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_app_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - school_network

  backend:
    image: sohail185/backend-app:${IMAGE_TAG}
    container_name: backend_app
    restart: always
    environment:
      DB_HOST: school-app_mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: school_app_db
      PORT: 3500
      HOST: 0.0.0.0
    ports:
      - "3500:3500"
    depends_on:
      - mysql
    networks:
      - school_network

  frontend:
    image: sohail185/frontend-app:${IMAGE_TAG}
    container_name: frontend_app
    restart: always
    environment:
      REACT_APP_API_URL: http://192.168.217.224:3500
      FRONTEND_URL: http://192.168.217.224:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - school_network

volumes:
  mysql_data:

networks:
  school_network:
    driver: bridge
