version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_app_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - school_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  backend:
    image: sohail185/backend-app:latest
    env_file:
      - ./backend/.env
    ports:
      - target: 3500
        published: 3500
        protocol: tcp
        mode: host
    networks:
      - school_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: sohail185/frontend-app:latest
    env_file:
      - ./frontend/.env
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - school_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  mysql_data:

networks:
  school_network:
    driver: overlay

