version: "3.8"

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - school_network
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_app_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - school_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  backend:
    image: sohail185/backend-app:latest
    env_file:
      - ./backend/.env
    networks:
      - school_network
    deploy:
      replicas: 2

  frontend:
    image: sohail185/frontend-app:latest
    env_file:
      - ./frontend/.env
    networks:
      - school_network
    deploy:
      replicas: 2

volumes:
  mysql_data:

networks:
  school_network:
    driver: overlay

configs:
  nginx_conf:
    external: true
