version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_app_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"   # Host:Container port mapping
    networks:
      - school_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  backend:
    image: sohail185/backend-app:latest
    env_file:
      - ./backend/.env
    ports:
      - "3500:3500"
    networks:
      - school_network
    deploy:
      replicas: 2  # Swarm will distribute automatically across manager + workers

  frontend:
    image: sohail185/frontend-app:latest
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - school_network
    deploy:
      replicas: 2   # Swarm will distribute automatically across manager + workers

volumes:
  mysql_data:

networks:
  school_network:
    driver: overlay
